#!/bin/bash

echo "Cleanup...";
rm -fr app/static/lib/*
rm -fr bower_components/
echo "Downloading..."
bower install momentjs bootstrap angular-route angular-translate-loader-static-files angular-translate-storage-cookie angular-translate-storage-local --allow-root
echo "Creating dirs..."
mkdir app/static/lib/bootstrap
mkdir -p app/static/lib/angularjs/plugins/angular-route
mkdir app/static/lib/angularjs/plugins/angular-translate
mkdir app/static/lib/angularjs/plugins/angular-cookies/
mkdir app/static/lib/momentjs
mkdir app/static/lib/fonts/
mkdir app/static/lib/jquery

echo "Copying files into static/lib..."
# angular
cp bower_components/angular/angular.min.js app/static/lib/angularjs/
# angular-route
cp bower_components/angular-route/angular-route.min.js app/static/lib/angularjs/plugins/angular-route/
# angular-translate
cp bower_components/angular-translate/angular-translate.min.js app/static/lib/angularjs/plugins/angular-translate/
cp bower_components/angular-cookies/angular-cookies.min.js app/static/lib/angularjs/plugins/angular-cookies/
cp bower_components/angular-translate-loader-static-files/angular-translate-loader-static-files.min.js app/static/lib/angularjs/plugins/angular-translate/
cp bower_components/angular-translate-storage-cookie/angular-translate-storage-cookie.min.js app/static/lib/angularjs/plugins/angular-translate/
cp bower_components/angular-translate-storage-local/angular-translate-storage-local.min.js app/static/lib/angularjs/plugins/angular-translate/
# bootstrap
cp bower_components/bootstrap/dist/css/bootstrap-theme.min.css app/static/lib/bootstrap/
cp bower_components/bootstrap/dist/css/bootstrap.min.css app/static/lib/bootstrap/
cp bower_components/bootstrap/dist/js/bootstrap.min.js app/static/lib/bootstrap/
cp bower_components/bootstrap/fonts/* app/static/lib/fonts/
# jquery
cp bower_components/jquery/dist/jquery.min.js app/static/lib/jquery/
# momentjs
cp bower_components/momentjs/min/moment.min.js app/static/lib/momentjs/

echo "Removing bower_components/..."
rm -fr bower_components/
echo "done."
